name: Daedalus
version: 1.0
main: fr.zelytra.daedalus.Daedalus
load: POSTWORLD
softdepend:
  - FastAsyncWorldEdit
api-version: 1.16
commands:

  settings:
    permission: daedalus.configuration
    description: Acces to configuration menu

  maze:
    aliases: lb
    permission: daedalus.configuration
    description: All maze commands

  structure:
    aliases: struct
    permission: daedalus.configuration
    description: Structure generator commands

  state:
    permission: daedalus.configuration
    description: Change game state

  dgive:
    permission: daedalus.configuration
    description: Give custom items

  revive:
    permission: daedalus.revive
    description: Revive a player

  wiki:
    description: Show item wiki

  coordinate:
    description: Share your location to your mates
    aliases:
      - co
      - loc
      - coo

  test:
    description: test command

  hadesrevive:
    description: Hades revive power

