name: Daedalus
version: ${project.version}
main: fr.zelytra.daedalus.Daedalus
commands:
  settings:
    description: permet de configurer la partie
api-version: 1.16

commands:
  maze:
    aliases: lb
    permission: daedalus.maze
    description: All maze commands